name: home_stop
description: gandu sale

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  zoomable_image: any

flutter:

  uses-material-design: true
  assets:
    - images/SP.png
    - images/Login Photo.jpeg

