name: home_stop
description: gandu sale

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  flutter_snake_navigationbar: ^0.3.0
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+1
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.1.4
  rflutter_alert:
  google_fonts:
  flutter_svg:
  email_validator: ^1.0.4
  flutter_auth_buttons: ^0.6.0
  credit_card: ^0.1.8
  google_maps_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  zoomable_image: any

flutter:

  uses-material-design: true
  assets:
    - images/SP.png
    - images/Login Photo.jpeg
    - images/shop.jpg
    - images/rat_star.svg
    - images/Nivea.jpg
    - images/Nivea_perfume.jpg
    - images/vaseline.jpg
    - images/Addidas_shoes.jpeg
    - images/apple_inc.jpg
    - images/HP_laptop.webp
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-BoldItalic.ttf

