# Generated by Django 3.0.3 on 2020-06-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posthandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='Item_Name', max_length=30)),
                ('company', models.IntegerField(db_column='Company')),
                ('cost', models.BigIntegerField(db_column='Cost')),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('oid', models.AutoField(db_column='Oid', primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('vid', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('did', models.IntegerField()),
                ('paymnt_method', models.CharField(max_length=30)),
                ('order_stat', models.CharField(max_length=10)),
                ('total_cost', models.FloatField()),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(db_column='Uid', primary_key=True, serialize=False)),
                ('usrname', models.CharField(db_column='Usrname', max_length=30, unique=True)),
                ('passwd', models.TextField(db_column='Passwd')),
                ('phno', models.CharField(db_column='Phno', max_length=15, unique=True)),
                ('email_id', models.TextField(db_column='Email_Id', unique=True)),
                ('fname', models.CharField(db_column='Fname', max_length=30)),
                ('mname', models.CharField(db_column='Mname', max_length=30)),
                ('lname', models.CharField(db_column='Lname', max_length=30)),
                ('lat', models.FloatField(db_column='Lat')),
                ('lon', models.FloatField(db_column='Lon')),
                ('address', models.TextField(db_column='Address')),
                ('online', models.IntegerField(db_column='Online')),
                ('type', models.CharField(db_column='Type', max_length=10)),
                ('date_of_join', models.DateTimeField(db_column='date of join')),
                ('api_key', models.CharField(max_length=30)),
                ('iv', models.TextField()),
                ('updated_time', models.DateTimeField()),
                ('verified', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='test22',
            name='tid',
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.OneToOneField(db_column='Cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Users')),
                ('payment_dets', models.TextField(blank=True, db_column='Payment_Dets', null=True)),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPersonal',
            fields=[
                ('did', models.OneToOneField(db_column='Did', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Users')),
                ('acc_dets', models.TextField(db_column='ACC_dets')),
                ('licence_no', models.CharField(db_column='Licence_no', max_length=30, unique=True)),
                ('licence_plt_no', models.CharField(db_column='Licence_plt_no', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Delivery_personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ord',
            fields=[
                ('oid', models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.OrderDetails')),
                ('qty', models.FloatField()),
            ],
            options={
                'db_table': 'ord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Users')),
                ('email', models.CharField(max_length=30)),
                ('hash', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField()),
                ('stat', models.IntegerField()),
            ],
            options={
                'db_table': 'user_verification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vid', models.OneToOneField(db_column='Vid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Users')),
                ('description', models.TextField(blank=True, null=True)),
                ('gst_code', models.CharField(blank=True, db_column='GST_Code', max_length=15, null=True)),
                ('acc_dets', models.TextField(blank=True, db_column='ACC Dets', null=True)),
                ('shop_name', models.CharField(db_column='Shop_Name', max_length=30)),
                ('type', models.CharField(db_column='Type', max_length=15)),
            ],
            options={
                'db_table': 'vendor',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test11',
        ),
        migrations.DeleteModel(
            name='Test22',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('cid', models.OneToOneField(db_column='Cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Customers')),
                ('msg', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewsRating',
            fields=[
                ('cid', models.OneToOneField(db_column='cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Customers')),
                ('review', models.TextField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'reviews/rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('vid', models.OneToOneField(db_column='Vid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.Vendor')),
                ('units', models.FloatField()),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
    ]
