# Generated by Django 3.0.3 on 2020-06-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posthandler', '0002_auto_20200613_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posthandler.OrderDetails')),
                ('qty', models.FloatField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='reviewsrating',
            table='reviews_rating',
        ),
        migrations.DeleteModel(
            name='Ord',
        ),
    ]
