# Generated by Django 3.0.3 on 2020-06-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posthandler', '0003_auto_20200623_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOrder',
            fields=[
                ('mid', models.AutoField(db_column='Mid', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(db_column='CreatedDate')),
                ('costpermonth', models.FloatField(db_column='CostPerMonth')),
            ],
            options={
                'db_table': 'Monthly_Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Morder',
            fields=[
                ('moid', models.OneToOneField(db_column='Moid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posthandler.MonthlyOrder')),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'Morder',
                'managed': False,
            },
        ),
    ]
